# Generated by Django 4.2 on 2024-02-11 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('nombres', models.CharField(max_length=63)),
                ('apellido_pat', models.CharField(max_length=31)),
                ('apellido_mat', models.CharField(max_length=31)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(default='Asoc. de Vivienda "El Mirador Zona C" Mz-A Lt-1', max_length=100)),
                ('celular', models.CharField(max_length=9)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('vivencia', models.BooleanField(default=False)),
                ('exonerado', models.BooleanField(default=False)),
                ('observaciones', models.TextField()),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socio_creado_por', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socio_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
